MEMORY_TYPE = 'sparse_kda'
SPARSE_KDA_ROUTER_LOSS_TYPE = 'bal'
SPARSE_KDA_BAL_LOSS_WEIGHT = 0.01
SPARSE_KDA_USE_SHARED_MEMORY = True
SPARSE_KDA_USE_ORACLE_ROUTER = True
SPARSE_KDA_TOP_K = 1
SPARSE_KDA_USE_LSH_WRITE = True
